### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by Zyles** [DennisSkoko/discord-bot#1]
Can you provide more guidance on how to start the bot?

First of all you are missing the namespace in your example.

Secondly I get the error:

```
PHP Fatal error: Declaration of Mybot::setup() must be compatible with DS\Bot::setup(Discord\Discord $discord) Discord\Websockets\Websocket $ws) in bot.php
```

**Comment by DennisSkoko** [comment]
Hi

Your error occurs because you didn't add the necessary parameters to the `setup()` function. You can check the parameter list from the example in README.md.

And about the missing namespace, can you specify which namespace is missing?

Didn't except anyone to actually use this mini framework. I wrote this because to make it easier for me to develop and was too poor to make it private. But I will recommend you use another framework because this one is outdated (uses [DiscordPHP](https://github.com/teamreflex/DiscordPHP) API v3.2.0). I'm waiting for v4 to come out and if it comes before the summer ends, I will then update this framework.

If you are still interested on using this framework I'm afraid I can only link a more in-depth [example](https://github.com/DennisSkoko/ingolf). This is a bot I'm developing but it's far from finished. I stopped working on it when v4 was announced.

Regards,
Dennis

**Comment by Zyles** [comment]
I copied your example straight of in the Readme.

And the namespace is DS\Bot; missing in the readme.

I'll check out your bot.

**Comment by Zyles** [comment]
Got it to work. You need these namespaces in your example:

```
use DS\Bot;
use Discord\Discord;
use Discord\WebSockets\WebSocket;
```

Thanks. Now I can make my bot.

**Comment by DennisSkoko** [comment]
Fixed on this [commit](https://github.com/DennisSkoko/discord-bot/commit/cf478311f2499c353a94074cb14777d933ddaad3).

Let me know if you have any further problems.

Regards
Dennis
